### ISSUE TITLE
Does gnbsim support usrp or other SDR？

### ISSUE THREAD

**Issue by shuimoshusheng** [AlohaLuo/gnbsim-backup#1]

**Comment by oaisara** [comment]
I have tried to use gnbsim with open air interface core network. I followed steps mentioned in the documentation "https://gitlab.eurecom.fr/oai/cn5g/oai-cn5g-fed/-/blob/master/docs/DEPLOY_SA5G_SLICING.md". The ping tests worked well. However, when i tried to execute the example file in the gnbsim docker container, I got this error: decoding id (110) not supported yet. It seems like there is problem in decoding ngap messages from the communication between the gnodeb and the AMF
